version: "3"

services:
  apache:
    image: gmateu/soc-wp1
    depends_on:
     - database 
    volumes:
     - ./data/web:/var/www/html 
    labels:
     - "traefik.backend=wordpress1"
     - "traefik.frontend.rule=Host:wp1.soc.imerir"
     - "traefik.docker.network=traefik_default"
    networks:
     - proxy
     - default
  database:
    image: mysql:5.6
    env_file: 
     - database.env
    volumes:
     - ./data/database/:/var/lib/mysql
    labels:
     - "traefik.enable=false"

networks:
  default:
    ipam:
      driver: default
      config:
       - subnet: 10.255.1.32/28
  proxy:
    external:
      name: traefik_default
